// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYP0aHRroNphUKdAUEqg_Uay8moYzLGco',
    appId: '1:612438421763:web:7fd0dd5a1fd094f7e6f936',
    messagingSenderId: '612438421763',
    projectId: 'eyevolve-5cdac',
    authDomain: 'eyevolve-5cdac.firebaseapp.com',
    databaseURL: 'https://eyevolve-5cdac-default-rtdb.firebaseio.com',
    storageBucket: 'eyevolve-5cdac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYhTJXPAm-Ml01vtC0FX-B4rWaNZax_qk',
    appId: '1:612438421763:android:7b0f740bc7f56793e6f936',
    messagingSenderId: '612438421763',
    projectId: 'eyevolve-5cdac',
    databaseURL: 'https://eyevolve-5cdac-default-rtdb.firebaseio.com',
    storageBucket: 'eyevolve-5cdac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK6rZYVSPJAeFEFI9IOkZ20cYxXkaGEug',
    appId: '1:612438421763:ios:4ef11bba9c4f5c1ce6f936',
    messagingSenderId: '612438421763',
    projectId: 'eyevolve-5cdac',
    databaseURL: 'https://eyevolve-5cdac-default-rtdb.firebaseio.com',
    storageBucket: 'eyevolve-5cdac.firebasestorage.app',
    iosBundleId: 'com.example.eyeVolve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK6rZYVSPJAeFEFI9IOkZ20cYxXkaGEug',
    appId: '1:612438421763:ios:4ef11bba9c4f5c1ce6f936',
    messagingSenderId: '612438421763',
    projectId: 'eyevolve-5cdac',
    databaseURL: 'https://eyevolve-5cdac-default-rtdb.firebaseio.com',
    storageBucket: 'eyevolve-5cdac.firebasestorage.app',
    iosBundleId: 'com.example.eyeVolve',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYP0aHRroNphUKdAUEqg_Uay8moYzLGco',
    appId: '1:612438421763:web:7d5d7215aceb6e7de6f936',
    messagingSenderId: '612438421763',
    projectId: 'eyevolve-5cdac',
    authDomain: 'eyevolve-5cdac.firebaseapp.com',
    databaseURL: 'https://eyevolve-5cdac-default-rtdb.firebaseio.com',
    storageBucket: 'eyevolve-5cdac.firebasestorage.app',
  );
}
